/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dragongate_technologies_mcOptCal_lsm */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm
#define _Included_com_dragongate_technologies_mcOptCal_lsm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dragongate_technologies_mcOptCal_lsm
 * Method:    calcAsianOptionValueJNI
 * Signature: (Lcom/dragongate_technologies/mcOptCal/Calc;Lcom/dragongate_technologies/mcOptCal/LsmParams;Lscala/util/Random;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dragongate_1technologies_mcOptCal_lsm_calcAsianOptionValueJNI
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_Eqn */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_Eqn
#define _Included_com_dragongate_technologies_mcOptCal_lsm_Eqn
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_Number */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_Number
#define _Included_com_dragongate_technologies_mcOptCal_lsm_Number
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_Number__ */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_Number__
#define _Included_com_dragongate_technologies_mcOptCal_lsm_Number__
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_Symbol */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_Symbol
#define _Included_com_dragongate_technologies_mcOptCal_lsm_Symbol
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_Symbol__ */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_Symbol__
#define _Included_com_dragongate_technologies_mcOptCal_lsm_Symbol__
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_Operator */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_Operator
#define _Included_com_dragongate_technologies_mcOptCal_lsm_Operator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_Operator__ */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_Operator__
#define _Included_com_dragongate_technologies_mcOptCal_lsm_Operator__
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_Function */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_Function
#define _Included_com_dragongate_technologies_mcOptCal_lsm_Function
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_Function__ */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_Function__
#define _Included_com_dragongate_technologies_mcOptCal_lsm_Function__
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_ErrorText */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_ErrorText
#define _Included_com_dragongate_technologies_mcOptCal_lsm_ErrorText
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_ErrorText__ */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_ErrorText__
#define _Included_com_dragongate_technologies_mcOptCal_lsm_ErrorText__
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_FunctionOp */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_FunctionOp
#define _Included_com_dragongate_technologies_mcOptCal_lsm_FunctionOp
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_FunctionOp__ */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_FunctionOp__
#define _Included_com_dragongate_technologies_mcOptCal_lsm_FunctionOp__
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_EqnParsers__ */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_EqnParsers__
#define _Included_com_dragongate_technologies_mcOptCal_lsm_EqnParsers__
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_BracketedOp */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_BracketedOp
#define _Included_com_dragongate_technologies_mcOptCal_lsm_BracketedOp
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_BracketedOp__ */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_BracketedOp__
#define _Included_com_dragongate_technologies_mcOptCal_lsm_BracketedOp__
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_ArithmeticOp */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_ArithmeticOp
#define _Included_com_dragongate_technologies_mcOptCal_lsm_ArithmeticOp
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_dragongate_technologies_mcOptCal_lsm_ArithmeticOp__ */

#ifndef _Included_com_dragongate_technologies_mcOptCal_lsm_ArithmeticOp__
#define _Included_com_dragongate_technologies_mcOptCal_lsm_ArithmeticOp__
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
